# Generated by Django 3.2.4 on 2021-06-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idboleta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechaboleta', models.DateField()),
                ('formapago', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rutcliente', models.CharField(max_length=20)),
                ('nombrecliente', models.CharField(max_length=50)),
                ('telefonocliente', models.IntegerField()),
                ('correocliente', models.CharField(max_length=50)),
                ('estadocliente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idboleta', models.BigIntegerField()),
                ('idproducto', models.BigIntegerField()),
                ('cantidadproducto', models.BigIntegerField()),
                ('totalventa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalleventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Familiaproducto',
            fields=[
                ('idfamilia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descfamilia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'familiaproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiado',
            fields=[
                ('idfiado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idcliente', models.BigIntegerField()),
                ('estadofiado', models.CharField(max_length=20)),
                ('totalfiado', models.BigIntegerField()),
            ],
            options={
                'db_table': 'fiado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=50)),
                ('descproducto', models.CharField(max_length=150)),
                ('fechavencimiento', models.DateField(blank=True, null=True)),
                ('preciocompra', models.BigIntegerField(blank=True, null=True)),
                ('precioventa', models.BigIntegerField(blank=True, null=True)),
                ('stockproducto', models.IntegerField(blank=True, null=True)),
                ('stockcriticoproducto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('telefonoproveedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('correoproveedor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rubroproveedor',
            fields=[
                ('idrubro', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descrubro', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rubroproveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoproducto',
            fields=[
                ('idtipo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('desctipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipoproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipousuario', models.CharField(max_length=50)),
                ('nombreusuario', models.CharField(max_length=20)),
                ('contrasenausuario', models.CharField(max_length=50)),
                ('telefonousuario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
