# Generated by Django 3.1.4 on 2021-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenDonaJuanita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalleboleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idboleta', models.BigIntegerField()),
                ('idproducto', models.BigIntegerField()),
                ('cantidadproducto', models.BigIntegerField()),
                ('totalventa', models.BigIntegerField()),
                ('valorproducto', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalleboleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadopedido',
            fields=[
                ('idestado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descestado', models.BigIntegerField()),
            ],
            options={
                'db_table': 'estadopedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpedido', models.BigIntegerField()),
                ('fechapedido', models.BigIntegerField()),
                ('idestado', models.BigIntegerField()),
                ('idproducto', models.BigIntegerField()),
                ('fechallegada', models.BigIntegerField()),
                ('idusuario', models.BigIntegerField()),
                ('totalproducto', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Detalleventa',
        ),
    ]
